################################################################################
#  配置文件
#
# 1) 环境基本参数:
#    width, height, depth: 3D 网格大小
#    obstacle_count: 障碍物数量
#    random_seed: 若不为 null，则固定随机种子，方便复现
#
# 2) num_runs: 表示要生成多少个随机环境; 对每个环境都对比多算法
#
# 3) 起点终点:
#    start_random, goal_random: 若为 true，则随机起/终点
#    start_position, goal_position: 若不随机，则使用固定坐标
#
# 4) OctoMap 配置:
#    use_octomap: 是否启用 OctoMap
#    coarse_resolution: 粗层分辨率(如4)
#    fine_resolution:   细层分辨率(如1)
#
# 5) compare_algorithms: 是否比较多算法; 若true, 一次性跑(bfs, astar, opt, rrt, rrt_star, coarse_to_fine)
#    若false, 仅跑 config["algorithm"] 指定的算法
#
# 6) 可视化:
#    visualization_mode: "voxel_scatter" 或 "voxel_plot"
#    show_start_goal_in_vis: 是否在图里标出起点(绿三角)和终点(红叉)
#
# 7) 各算法的参数:
#    - bfs_settings: neighbor_mode="6" or "26"
#    - astar_settings: neighbor_mode="6"/"26", heuristic="euclidean"/...
#    - opt_settings: PotentialField 的最大迭代 steps
#    - rrt_settings: step_size, max_iter, goal_threshold
#    - rrt_star_settings: 同上, 另加 rewire_radius
#    - coarse_to_fine_settings: 
#       coarse_planner: "bfs"/"astar"/"rrt"
#       fine_planner:   "bfs"/"astar"/"rrt"
#       neighbor_mode:  "6" or "26"  (供bfs/astar使用)
################################################################################

width: 100
height: 100
depth: 100

obstacle_count: 80
random_seed: null

num_runs: 5

start_random: true
goal_random: true
start_position: [0, 0, 0]
goal_position: [29, 29, 29]

use_octomap: true
coarse_resolution: 4
fine_resolution: 1

compare_algorithms: true
algorithm: "rrt_star"

visualization_mode: "voxel_scatter"
show_start_goal_in_vis: true

bfs_settings:
  neighbor_mode: "6"

astar_settings:
  neighbor_mode: "6"
  heuristic: "euclidean"

opt_settings:
  max_steps: 2000

rrt_settings:
  step_size: 3
  max_iter: 1000
  goal_threshold: 4.0

rrt_star_settings:
  step_size: 3
  max_iter: 1000
  goal_threshold: 4.0
  rewire_radius: 3.0

coarse_to_fine_settings:
  coarse_planner: "bfs"
  fine_planner: "astar"
  neighbor_mode: "6"
